### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by xinghuanluo**
Hi Sean,

I found a couple of typos when using this package.

### CODE REVIEW

**Comment by skhiggins** [comment]
Will it work with these edits if the user doesn't specify the `y_labgap`, `ylabel_format` etc. options? We need the code written in such a way that there won't be an error generated even if they don't specify those options. My way ensures there is no error if they don't specify `y_labgap`, but it forces the user to write `y_labgap(labgap(...))` which I agree is more tedious than if they can write `y_labgap(...)`.

**Comment by xinghuanluo** [comment]
I just tried it on my PC and there is no problem if the user doesn't specify `y_labgap`, `ylabel_format` etc. But, the bad thing is that, the user may not know which variables have been specified in this package unless they open the ado file and check by themselves. For example, if the user writes `xlabel(0(5)25,  angle(45))` and there will be an error since `angle()` has already been specified by `x_angle` in the package.

**Comment by skhiggins** [comment]
Are you sure that would lead to an error? Can you test it? I thought if someone specifies an argument twice Stata just uses the second of the two.

**Comment by xinghuanluo** [comment]
For example, if you run the code below, 
```stata
version 16.1 
sysuse "auto2.dta", clear

graph_options
	
#delimit ;
twoway scatter mpg trunk, 
	title("Cars with more trunk space have worse mpg", size(small) `title_options')
;
#delimit cr
```
The result then will be 
image

This is because the ado file has already defined `size()` in `title_options`. 
https://github.com/skhiggins/Stata_guide/blob/4a041ccaae623414ed53aee3e23c107128f643f0/scripts/programs/graph_options.ado#L62

But if you remove `size(small)`, it will run without any errors. 
```stata
version 16.1 
sysuse "auto2.dta", clear

graph_options
	
#delimit ;
twoway scatter mpg trunk, 
	title("Cars with more trunk space have worse mpg",  `title_options')
;
#delimit cr
```

**Comment by skhiggins** [comment]
#5

**Pull request merged**
